"""Knowledge-store protocol: the only boundary between agents and KG data."""

from __future__ import annotations

from typing import Protocol

from debug_agent_system.core.contracts import Candidate, LockedSubgraph


class KGStore(Protocol):
    errors: list[dict]

    def search_errors(self, query: str, limit: int = 5) -> list[Candidate]: ...
    def load_locked_subgraph(self, error_id: str) -> LockedSubgraph: ...
    def read_review_queue(self, name: str) -> list[dict]: ...
    def write_review_queue(self, name: str, data: list[dict]) -> None: ...
    def dry_run_apply(self, candidate: dict) -> dict: ...
    def apply_approved(self, candidate: dict) -> dict: ...
    def apply_required_info_approved(self, candidate: dict) -> dict: ...
